# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-13 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.CharField(max_length=20)),
                ('test2', models.CharField(max_length=30)),
                ('test3', models.FloatField()),
            ],
        ),
    ]
