# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-16 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_study_4', '0004_auto_20181116_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.BooleanField()),
            ],
            options={
                'verbose_name': 'wife',
                'verbose_name_plural': 'wife',
            },
        ),
    ]
