# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-16 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_study_4', '0005_wife'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wife',
            name='gender',
        ),
    ]
