# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-16 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_study_4', '0007_wife_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_study_4.Publisher', verbose_name='出版社'),
        ),
        migrations.AlterField(
            model_name='wife',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='wife',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_study_4.Author', verbose_name='husband  '),
        ),
        migrations.AlterField(
            model_name='wife',
            name='name',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
    ]
