# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-19 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_study_4', '0008_auto_20181116_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='django_study_4.Author'),
        ),
    ]
