# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-19 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_study_4', '0009_book_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='authors',
            field=models.ManyToManyField(to='django_study_4.Author', verbose_name='签约作者'),
        ),
    ]
