# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-19 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_study_5', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remark',
            old_name='is_active',
            new_name='is_save',
        ),
    ]
