# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-20 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_study_5', '0002_auto_20181119_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=3)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
